version: '3.0'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env  
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis
    ports:
    - "6379:6379"
  app:
    image: leaguex-app
    ports: 
        - 4500:4000
    env_file:
      - ./.env  








